//
// Generated file, do not edit! Created by opp_msgtool 7.0 from Task.msg.
//

#ifndef __TASK_M_H
#define __TASK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0700
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Task;
/**
 * Class generated from <tt>Task.msg:2</tt> by opp_msgtool.
 * <pre>
 * message Task
 * {
 *     double taskLength;
 * }
 * </pre>
 */
class Task : public ::omnetpp::cMessage
{
  protected:
    double taskLength = 0;

  private:
    void copy(const Task& other);

  protected:
    bool operator==(const Task&) = delete;

  public:
    Task(const char *name=nullptr, short kind=0);
    Task(const Task& other);
    virtual ~Task();
    Task& operator=(const Task& other);
    virtual Task *dup() const override {return new Task(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getTaskLength() const;
    virtual void setTaskLength(double taskLength);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Task& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Task& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Task *fromAnyPtr(any_ptr ptr) { return check_and_cast<Task*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TASK_M_H

